apiVersion: v1
kind: Secret
metadata:
  name: wso2server-secret
  namespace: istio-system
type: Opaque
stringData:
  apim-url: https://wso2apim-with-analytics-apim-service.wso2.svc:9443
  server-token: YWRtaW46YWRtaW4=
---
apiVersion: v1
kind: Service
metadata:
  name: wso2adapterservice
  namespace: istio-system
  labels:
    app: wso2adapter
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 44225
    targetPort: 44225
  selector:
    app: wso2adapter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2adapter
  namespace: istio-system
  labels:
    app: wso2adapter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wso2adapter
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - name: wso2adapter
        image: pubudu/wso2adapter:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 44225
        volumeMounts:
        - name: server-cert-volume
          mountPath: "/etc/wso2/server-cert"
          readOnly: true
        - name: wso2server-secret-volume
          mountPath: "/etc/wso2/server-credentials"
          readOnly: true
      volumes:
        - name: server-cert-volume
          secret:
            secretName: server-cert
        - name: wso2server-secret-volume
          secret:
            secretName: wso2server-secret